# Generated by Django 5.0.3 on 2024-04-01 18:35

import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test', max_length=100)),
                ('domain', models.CharField(max_length=300, null=True)),
                ('year_founded', models.CharField(max_length=300, null=True)),
                ('size_range', models.CharField(max_length=300, null=True)),
                ('locality', models.CharField(max_length=300, null=True)),
                ('country', models.CharField(max_length=300, null=True)),
                ('linkedin_url', models.CharField(max_length=300, null=True)),
                ('current_employee_estimate', models.CharField(max_length=300, null=True)),
                ('total_employee_estimate', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(default=task.models.generate_upload_id, editable=False, max_length=32, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
